// regenerates src/emoji-data.ts, the :shortcode: table for the emoji plugin, from GitHub's gemoji
// database. every alias gets an entry, so :+1: and :thumbsup: both work.
import { mkdir, writeFile } from 'node:fs/promises';

const res = await fetch('https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json');
if (!res.ok) throw new Error(`emoji.json: ${res.status}`);
const list = await res.json();

const map = {};
for (const entry of list) {
	for (const alias of entry.aliases) map[alias] = entry.emoji;
}

const out =
	'// generated by scripts/gen-emoji.mjs from https://github.com/github/gemoji - do not edit\n' +
	`export const gemoji: Readonly<Record<string, string>> = ${JSON.stringify(map)};\n`;

await mkdir(new URL('../src/', import.meta.url), { recursive: true });
await writeFile(new URL('../src/emoji-data.ts', import.meta.url), out);
console.log(`${Object.keys(map).length} shortcodes`);
